// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcZHRPajhtuuXTF8WUKok3cKnTFoS39uU',
    appId: '1:330657617117:web:e752052af0048e821ff734',
    messagingSenderId: '330657617117',
    projectId: 'journal-e28a7',
    authDomain: 'journal-e28a7.firebaseapp.com',
    storageBucket: 'journal-e28a7.firebasestorage.app',
    measurementId: 'G-8N0DBJED9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAere7hqYBWavri8i_jZmHh10ewejjAeH8',
    appId: '1:330657617117:android:737f31cdbab649481ff734',
    messagingSenderId: '330657617117',
    projectId: 'journal-e28a7',
    storageBucket: 'journal-e28a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDlM2MzF8e2dwtbPvO5vqizGvxVJ59yPU',
    appId: '1:330657617117:ios:f9e126536fe715ce1ff734',
    messagingSenderId: '330657617117',
    projectId: 'journal-e28a7',
    storageBucket: 'journal-e28a7.firebasestorage.app',
    iosClientId: '330657617117-fdclcdtrvjbfcq42fi4uu88untafhjqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.journalCurs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDlM2MzF8e2dwtbPvO5vqizGvxVJ59yPU',
    appId: '1:330657617117:ios:f9e126536fe715ce1ff734',
    messagingSenderId: '330657617117',
    projectId: 'journal-e28a7',
    storageBucket: 'journal-e28a7.firebasestorage.app',
    iosClientId: '330657617117-fdclcdtrvjbfcq42fi4uu88untafhjqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.journalCurs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcZHRPajhtuuXTF8WUKok3cKnTFoS39uU',
    appId: '1:330657617117:web:c0b745318d98223d1ff734',
    messagingSenderId: '330657617117',
    projectId: 'journal-e28a7',
    authDomain: 'journal-e28a7.firebaseapp.com',
    storageBucket: 'journal-e28a7.firebasestorage.app',
    measurementId: 'G-CKVD4D49E7',
  );
}
